### ISSUE TITLE
ability to query 5 companies by using OFFSET

### ISSUE THREAD

**Issue by jakecastelli** [Kay-Yuan/help-me-apply-api#12]
`/company` GET endpoint does not have ability to query only 5 companies at a time, every time a request comes in it will query all the companies and return to the user, this is not considered as good practice.

improvement to #10

**Comment by Kay-Yuan** [comment]
## http response codes
1. [Informational responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#information_responses) (100–199)
2. [Successful responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses) (200–299)
3. [Redirection messages](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#redirection_messages) (300–399)
4. [Client error responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) (400–499)
5. [Server error responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses) (500–599)

**Comment by Kay-Yuan** [comment]
## SQL limit & offset
Can be found at knex doc.
