### ISSUE TITLE
user has ability to create a job

### ISSUE THREAD

**Issue by jakecastelli** [Kay-Yuan/help-me-apply-api#6]
1. create a new migration - for job table (fields?)
2. create an endpoint `/job/create`
3. validate body
4. insert into db

**Comment by Kay-Yuan** [comment]
`
// 1. To create a new knexfile
npx knex init

// or for .ts

npx  knex init -x ts

// 2. To create migration files to the specified directory (default migrations)

npx knex migrate:make job_table

// 3. Update the database

npx knex migrate:latest
`

**Comment by jakecastelli** [comment]
job table got two new columns, see commit: a2338fff18cabb3e1d565490c74c42878e9658fc
